name: Greetings

on: [pull_request, issues]

jobs:
  greeting: Hello there fella, thanks for joining us!
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Something is wrong isn't it bud?'' first issue'
        pr-message: 'Message that will be displayed on users'' first pr'
